### PR TITLE
Update solidity and ipfs uris for transferable pkg

### PR DESCRIPTION
**Pull request by njgheorghita**
Update solidity version used in `transferable.sol`
Update ipfs links for `transferable` and `owned` pkg

### CODE REVIEW

**Comment by njgheorghita** [comment]
@gnidan good nitpick - I was thinking about that, and brief scan of the style guide couldn't find - i'm down to capitalize filenames. should we also capitalize the package name then?

**Comment by njgheorghita** [comment]
Actually - i'm good with capitalizing filename - and leaving package name uncapitalized. Not sure we need to push for a capitalized package name convention

**Comment by gnidan** [comment]
Agreed that package names should be lowercase

**Comment by njgheorghita** [comment]
mmmm. kebabs

**Comment by davesque** [comment]
Did you notice my comment about the inconsistent indentation in `examples/transferable/1.0.0.json`?

**Pull request merged**
