### PR TITLE
Refactor names of use-cases

### PR DESCRIPTION
**Pull request by njgheorghita**
I found the names of the use-cases to be occasionally clunky and difficult to grok. I went through and tried to improve this - though whether I accomplished this is debatable. Please suggest any changes you think might help - and I'll add them in. Or if you feel the old name conventions were more descriptive or less redundant - I'm not married to the suggestions made here.

[Preview](http://ethpm.github.io/ethpm-spec/contrib/ethpm/definitions/)

### CODE REVIEW

**Comment by gnidan** [comment]
@njgheorghita could you target `eip-1123` for this? Or I can just merge #106 now.

Otherwise, this looks great! I love the keywords breakout

**Comment by gnidan** [comment]
Sorry for continually breaking your merges!

**Comment by njgheorghita** [comment]
@gnidan Haha, no worries man - i'll take care of it when I get back from lunch

**Comment by njgheorghita** [comment]
@gnidan Updated - good to merge if it's looking good with you

**Pull request merged**
