### PR TITLE
Update owned solidity and ipfs links

### PR DESCRIPTION
**Pull request by njgheorghita**
Updated solidity version used in `owned.sol`
Updated & pinned ipfs uri's containing documentation and source solidity

### CODE REVIEW

**Comment by njgheorghita** [comment]
Is there any benefit to coming up with a suggested standard format for the linked documentation? Or is it better to just leave it open-ended?

**Comment by davesque** [comment]
Do you mean a standard format as in markdown, rst, html?

**Comment by davesque** [comment]
@njgheorghita These changes look good.  You didn't request review from me but feel free to merge.

**Comment by njgheorghita** [comment]
@davesque thanks! i was thinking more on what information to include in the documentation - but also the file type. My thinking is if we want to encourage writing / linking documentation then a standard of what information is "recommended" to include might help. But, i'm also not sure if this is really worth "encouraging" and should be entirely left up to the package creator

**Comment by gnidan** [comment]
What are your thoughts about updating the style conventions to match the [Solidity Style Guide](https://solidity.readthedocs.io/en/v0.4.24/style-guide.html)

(ie. camelcase, uppercase contracts, etc.)

**Comment by njgheorghita** [comment]
@gnidan Yeah, definitely. Updating now

**Comment by davesque** [comment]
I wonder if some of the improper stylistic elements were transferred from the solidity documentation here: https://solidity.readthedocs.io/en/develop/contracts.html#function-modifiers ?

**Comment by njgheorghita** [comment]
@gnidan @davesque Most likely - I'd be surprised if all the code throughout the solidity docs are in line with the style guide. Holler if I missed something

**Pull request merged**
